### ISSUE TITLE
Error in LW/Windows

### ISSUE THREAD

**Issue by LinkFly** [eudoxia0/find-port#1]
Error USOCKET:INVALID-SOCKET-ERROR when calling:

> (find-port:port-open-p 63342) ;;63342 - busy, if port not busy - return 0
> Error: The condition #<USOCKET:INVALID-SOCKET-ERROR 22943348> occurred

(find-port:find-port)
Error: The condition #<USOCKET:INVALID-SOCKET-ERROR 22979E50> occurred

**Comment by eudoxia0** [comment]
I can confirm that this works on SBCL as well, and I believe it can be solved by changing the default port range. Let me see what I find.

**Comment by LinkFly** [comment]
Yes, it is desirable to warn that tested on SBCL.
But i am using LW, and correct working on it - desirable for me)

**Comment by LinkFly** [comment]
I am self corrected code usocket - after my pull request accepted, your code will be working!
(see https://github.com/usocket/usocket/pull/2 )

**Comment by eudoxia0** [comment]
Did you test this after my change to the default port range? (Haven't had a chance to re-test on Windows)

**Comment by LinkFly** [comment]
I am tested now, all ok:
CL-USER 9 > (find-port:find-port)
40000

**Comment by eudoxia0** [comment]
Ok, I'll close this as fixed then.
